spring:
  h2:
    console:
      enabled: true
name: prod-YAML
environment: production
enabled: true
server:
  address: localhost
  port: 8080 
resoucesServer: http://localhost:5001
createUserPath: /api/createUser
secret: secret